### ISSUE TITLE
Was wir noch machen müssen

### ISSUE THREAD

**Issue by Mozartuss** [dpekez/DEEZNUTZ#12]
## TODO

- [x] Highscores mit Map als Speicherstruktur (Aufgabe 8, Teil 2) 🔥🔥🔥
- [x] einstellbare Spielschritte nach denen das Spiel pausiert (Aufgabe 8, Teil 2) 🔥🔥🔥
- [x] Collection-API statt EntitySet-Array (Aufgabe 8, Teil 1)🔥🔥
- [x] Highscores in Datei speichern und bei Neustart einlesen (Aufgabe 9, Teil 2)🔥🔥
- [x] dynamisches Laden der Botconfig über BoardConfig (Aufgabe 8, Teil 2)
- [x] Logger wo nötig einfügen im Stile von:
`Logger.getLogger(Launcher.class.getName()).finer("MELDUNG");`
Teilweise schon geschehen, Altbestände schwirren aber noch im Code herum.
Bei Altbeständen den static Logger aus der Klasse rausnehmen nicht vergessen!
- [x] Dokumentation Aufgabe 9, Teil 4 (Klassendiagramm, JavaDoc, HTML generieren, Anleitung für Aussenstehende die Bots programmieren wollen)
- [x] JUnit-Tests vervollständigen, **schon abgenommen -> nicht wichtig** (viel schreib Arbeit)
- [x] Logger-Konfiguration über Properties-Datei (Aufgabe 9, Teil 1)
- [x] Bot-KI stetig verbessern

**Comment by dpekez** [comment]
[ x] Collection-API statt EntitySet-Array (Aufgabe 8, Teil 1)

See commit:

https://github.com/dpekez/DEEZNUTZ/commit/f43f6f2176cd27ba449ea719e00137f9b33a2bb3

**Comment by dpekez** [comment]
- [x] Highscores in Datei speichern und bei Neustart einlesen (Aufgabe 9, Teil 2)

erledigt

**Comment by dpekez** [comment]
- [x] Highscores mit Map als Speicherstruktur (Aufgabe 8, Teil 2)

erledigt

**Comment by Mozartuss** [comment]
- [x] JUnit-Tests vervollständigen, schon abgenommen -> nicht wichtig (viel schreib Arbeit)

erledigt
`nextStep` methode für `BadBeast` und `XYsupport` mit `randomMoveVector`

**Comment by Mozartuss** [comment]
- [ ] Dokumentation Aufgabe 9, Teil 4 (Klassendiagramm, JavaDoc, HTML generieren, Anleitung für Aussenstehende die Bots programmieren wollen)

das Klassendiagramm ist fertig die Documentation noch nicht

**Comment by Mozartuss** [comment]
alles ist fertig soweit ich weiß
